### ISSUE TITLE
memory error with big capture

### ISSUE THREAD

**Issue by Armonkee** [KimiNewt/pyshark#72] opened 2015-03-31 15:36 UTC
If I try to read a big Wireshark capture file with over 88000 captures, pyshark crashes after several thousands of packets (the number varies, even with the same capture file)
with a MemoryError:

  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 167, in _packets_from_tshark_sync
    self._get_packet_from_stream(tshark_process.stdout, data, psml_structure=psml_structure))
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
MemoryError 

I shrunk the Python program itself to a basic loop:

cap=pyshark.FileCapture(capture+".pcapng",keep_packets=False) 
p=0
start=time.time()
for packet in cap:
    p+=1
    if p%500 ==0:
        print p,time.time()-start
        start=time.time()

The output also shows that the program slows down while working its way through the packets
(indication of a memory leak?):
500 2.42000007629
1000 3.33999991417
1500 5.38499999046
2000 7.25200009346
2500 9.28200006485
3000 11.371999979
3500 13.3539998531
4000 15.4560000896
4500 17.6549999714
5000 19.7650001049
5500 21.7889997959
6000 24.0099999905
6500 26.1820001602
7000 28.4779999256
7500 30.6789999008
8000 32.9380002022

**Comment by Rainmaker52** [comment] 2015-04-20 23:33
I'm afraid I can confirm this. I have a capture file with > 500.000 packets in it, and the script I wrote is reading a pcapng file. The more packets are read, the slower the read gets.
Committed 500 packets to database in 3.9881327152252197 seconds. 125.37194118670737 records/sec
Committed 1000 packets to database in 12.0382981300354 seconds. 83.06821362772128 records/sec
Committed 1500 packets to database in 24.395216703414917 seconds. 61.48746243645864 records/sec
Committed 2000 packets to database in 41.17611646652222 seconds. 48.57184545037866 records/sec
Committed 2500 packets to database in 62.45869445800781 seconds. 40.026452571013124 records/sec
Committed 3000 packets to database in 88.47064304351807 seconds. 33.90955309532058 records/sec
Committed 3500 packets to database in 118.43529176712036 seconds. 29.552001997384533 records/sec
Committed 4000 packets to database in 153.36024022102356 seconds. 26.082379350241215 records/sec
Committed 4500 packets to database in 192.33607602119446 seconds. 23.396546663411378 records/sec
Committed 5000 packets to database in 236.38969564437866 seconds. 21.15151409708769 records/sec

I also disabled the actual insert statement, to ensure it was not caused by sqlite. Numbers are nearly identical when run without sqlite3.

I placed the capture file on a ramdisk, to rule out disk i/o as a factor.

**Comment by KimiNewt** [comment] 2015-05-06 08:35
Please attempt this with the latest revision

**Comment by Rainmaker52** [comment] 2015-05-07 12:25
Tried with latest git up until commit 040d91875f7d783c4726b622c8b903bd7dd5785d

Performance seems to be hugely improved:
> Starting...
> Committed 500 packets to database in 1.049614429473877 seconds. 476.3642120809656 records/sec
> Committed 1000 packets to database in 2.096942901611328 seconds. 476.88410998374457 records/sec
> Committed 1500 packets to database in 3.0374557971954346 seconds. 493.8339205640429 records/sec
> Committed 2000 packets to database in 4.1570539474487305 seconds. 481.109752806772 records/sec
> Committed 2500 packets to database in 5.379848957061768 seconds. 464.69689643970923 records/sec
> Committed 3000 packets to database in 6.434410095214844 seconds. 466.2428790749155 records/sec
> Committed 3500 packets to database in 7.637256383895874 seconds. 458.27955674070876 records/sec

Performance also seems to be constant throughout the operation, with only a slight performance degradation:
> Committed 93000 packets to database in 220.65093159675598 seconds. 421.48020143219236 records/sec
> Committed 93500 packets to database in 221.77180528640747 seconds. 421.6045365870674 records/sec
> Committed 94000 packets to database in 222.94951677322388 seconds. 421.6201064494466 records/sec
> Committed 94500 packets to database in 224.27641582489014 seconds. 421.3550450644411 records/sec

After ~95000 packets, I did get a 
> lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 1461, column 5243031

traceback. I am currently unsure whether this is because of my code, a bug in lxml, or a bug in pyshark. 

All in all, there seems to be a huge improvement. I'm not sure whether the original reporter can re-test with his code.

**Comment by Armonkee** [comment] 2015-05-08 14:01
Doesn't seem to work for me. Checking the version with
       print pkg_resources.get_distribution("pyshark").version
gives
       0.3.4

**Comment by KimiNewt** [comment] 2015-05-09 09:06
The new version is 0.3.5
I uploaded it to pypi now, so even if you install it via pip it should be fine.

**Comment by Armonkee** [comment] 2015-05-11 08:52
Perfect! 
V0.3.5 reads all my 88k packets - with hardly any performance degradation over time.

**Comment by KimiNewt** [comment] 2015-05-11 09:52
Cool

**Closed by KimiNewt** 2015-05-11 09:52 UTC

**Comment by malli02422** [comment] 2015-05-13 13:00
Hi ,
I found that you are working on the windows environment .
But I am not able to work with it , It is causing a problem for me when I try to run very basic test also 
Traceback (most recent call last):
  File "C:/pyexample/test.py", line 6, in <module>
    print cap[0]
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 63, in __getitem__
    self.next()
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 53, in next
    packet = self._packet_generator.send(None)
  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 162, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect


Please give me some tips to work with this library on the window envronment

**Comment by Rainmaker52** [comment] 2015-05-15 13:59
@malli02422 
The issue you are referring too, at first glance, seems to have nothing to do with this bug at all.
> WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect
seems to indicate an error in your code.

The bugtracker is not meant for these types of questions. Please use a forum, i.e. stackoverflow for that.

(hint; r"please check the impact of escape characters on a string")
